"""Unit tests for coverage gap detection, AI test generation, and static validation."""

import pytest
from travelguard.coverage_analyzer import CoverageAnalyzer
from travelguard.models import (
    ChangeSet,
    CoverageStatus,
    FileChange,
    ImpactAnalysisResult,
    JourneyImpact,
    RiskAssessment,
    SelectedTest,
    TestPriority,
)
from travelguard.test_generator import AITestGenerator
from travelguard.test_validator import TestValidator


def test_coverage_gap_detected_on_promo_code():
    """Verify coverage analyzer flags missing scenario when promo code is added."""
    analyzer = CoverageAnalyzer()

    changes = ChangeSet(files=[
        FileChange(
            path="frontend/src/components/PassengerForm.tsx",
            diff="""
+ const [promoCode, setPromoCode] = useState('');
+ const handleApplyPromo = () => { ... }
+ <input data-testid="promo-code-input" />
""",
            additions=5,
            deletions=0,
        )
    ])
    impact = ImpactAnalysisResult(
        summary="Added promotional discount code",
        change_type="ui",
        is_behavioral=True,
        affected_journeys=[
            JourneyImpact(
                journey_id="flight_booking",
                journey_name="Flight Booking & Confirmation",
                impact_level="high",
                capability="Promotional discount",
            )
        ],
        risk=RiskAssessment(level="high", score=80, reason="New coupon logic"),
        recommended_tests=[],
        business_impact="Fare calculation error",
    )
    selected_tests = [
        SelectedTest(
            test_id="flight-booking",
            file="tests/e2e/booking.spec.ts",
            name="End-to-End Flight Booking",
            priority=TestPriority.P0,
            reason="Core booking test",
            confidence=0.95,
        )
    ]

    coverage = analyzer.analyze(changes, impact, selected_tests)
    assert coverage.status == CoverageStatus.INSUFFICIENT
    assert len(coverage.missing_scenarios) >= 1
    assert "promo" in coverage.missing_scenarios[0].lower() or "discount" in coverage.missing_scenarios[0].lower()


def test_coverage_sufficient_when_no_new_capability():
    """Verify coverage analyzer returns SUFFICIENT for existing flows."""
    analyzer = CoverageAnalyzer()

    changes = ChangeSet(files=[
        FileChange(path="frontend/src/components/SearchForm.tsx", diff="+ button styling", additions=1, deletions=1)
    ])
    impact = ImpactAnalysisResult(
        summary="Search button styling",
        change_type="cosmetic",
        is_behavioral=False,
        affected_journeys=[],
        risk=RiskAssessment(level="low", score=10, reason="Cosmetic"),
        recommended_tests=[],
        business_impact="None",
    )
    selected_tests = [
        SelectedTest(
            test_id="flight-search",
            file="tests/e2e/search.spec.ts",
            name="Flight Search Workflow",
            priority=TestPriority.P1,
            reason="Search test",
            confidence=0.95,
        )
    ]

    coverage = analyzer.analyze(changes, impact, selected_tests)
    assert coverage.status == CoverageStatus.SUFFICIENT
    assert len(coverage.missing_scenarios) == 0


def test_validator_accepts_valid_code():
    """Verify TestValidator approves valid Playwright test code with AI notice."""
    valid_code = """/**
 * Generated by TravelGuard AI.
 * Review before promoting to the permanent test suite.
 */

import { test, expect } from '@playwright/test';

test('valid generated test', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('[data-testid="search-flights"]')).toBeVisible();
});
"""
    is_valid, errors = TestValidator.validate("dummy.spec.ts", valid_code)
    assert is_valid is True
    assert len(errors) == 0


def test_validator_rejects_arbitrary_timeout():
    """Verify TestValidator rejects tests using prohibited page.waitForTimeout()."""
    bad_code = """/**
 * Generated by TravelGuard AI.
 * Review before promoting to the permanent test suite.
 */

import { test, expect } from '@playwright/test';

test('bad test with sleep', async ({ page }) => {
  await page.goto('/');
  await page.waitForTimeout(5000);
  await expect(page.locator('h1')).toBeVisible();
});
"""
    is_valid, errors = TestValidator.validate("dummy.spec.ts", bad_code)
    assert is_valid is False
    assert any("page.waitForTimeout" in e for e in errors)


def test_validator_rejects_missing_ai_header():
    """Verify TestValidator rejects tests missing the required AI header notice."""
    no_header_code = """import { test, expect } from '@playwright/test';

test('test without header', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('h1')).toBeVisible();
});
"""
    is_valid, errors = TestValidator.validate("dummy.spec.ts", no_header_code)
    assert is_valid is False
    assert any("Generated by TravelGuard AI" in e for e in errors)
