"""AI-driven Playwright test generator grounded in existing test conventions."""

import logging
from pathlib import Path
import re
from typing import Optional

from app.llm.base import LLMResponse
from app.llm.router import LLMService, get_llm_service

from travelguard.models import ChangeSet, GeneratedTest, ImpactAnalysisResult
from travelguard.test_validator import TestValidator

logger = logging.getLogger("travelguard.generator")

TEST_GENERATOR_SYSTEM_PROMPT = """You are TravelGuard AI, an expert QA Engineer generating an automated Playwright TypeScript test for the SkyBook travel application.

REQUIREMENTS:
1. Use TypeScript and Playwright (@playwright/test).
2. Must follow existing SkyBook test conventions and data-testid attributes:
   - from-input, to-input, date-input, search-flights, select-flight, passenger-name, passenger-email, passenger-phone, book-flight, booking-confirmation, booking-id
3. Include the exact required disclaimer header:
/**
 * Generated by TravelGuard AI.
 * Review before promoting to the permanent test suite.
 */
4. DO NOT use page.waitForTimeout()! Use await expect(locator).toBeVisible() or similar proper Playwright assertions.
5. Provide clean, production-ready code with test('...', async ({ page }) => { ... }).
6. Return ONLY the TypeScript code block, or wrapped in ```typescript ... ```. Do not include introductory or concluding conversational prose.
"""


class AITestGenerator:
    """Generates targeted Playwright tests for uncovered capabilities."""

    def __init__(
        self,
        llm_service: Optional[LLMService] = None,
        target_dir: Optional[Path] = None,
        repo_root: Optional[Path] = None,
    ):
        self.llm_service = llm_service or get_llm_service()
        self.repo_root = repo_root or Path(__file__).resolve().parent.parent
        self.target_dir = target_dir or (self.repo_root / "tests" / "generated")
        self.target_dir.mkdir(parents=True, exist_ok=True)

    def _get_style_context(self) -> str:
        """Load snippet from existing booking test as few-shot style guide."""
        booking_spec = self.repo_root / "tests" / "e2e" / "booking.spec.ts"
        if booking_spec.exists():
            return booking_spec.read_text(encoding="utf-8")[:1000]
        return ""

    def _generate_fallback_code(self, scenario_name: str, diff_text: str) -> str:
        """Deterministic, convention-grounded fallback generator for promo codes / discounts."""
        code = """/**
 * Generated by TravelGuard AI.
 * Review before promoting to the permanent test suite.
 */

import { test, expect } from '@playwright/test';

test.describe('Generated: Promo Code Application Workflow', () => {
  test('customer can apply a promotional discount code during checkout', async ({ page }) => {
    // 1. Navigate to SkyBook and search flights
    await page.goto('/');
    await page.locator('[data-testid="from-input"]').fill('Delhi');
    await page.locator('[data-testid="to-input"]').fill('Dubai');
    await page.locator('[data-testid="date-input"]').fill('2026-09-15');
    await page.locator('[data-testid="search-flights"]').click();

    // 2. Select first available flight
    const selectBtn = page.locator('[data-testid="select-flight"]').first();
    await expect(selectBtn).toBeVisible();
    await selectBtn.click();

    // 3. Enter passenger details
    await page.locator('[data-testid="passenger-name"]').fill('Alice Traveler');
    await page.locator('[data-testid="passenger-email"]').fill('alice@example.com');
    await page.locator('[data-testid="passenger-phone"]').fill('+91 98765 43210');

    // 4. Apply promotional discount code
    const promoInput = page.locator('[data-testid="promo-code-input"]');
    if (await promoInput.isVisible()) {
      await promoInput.fill('FLY10');
      await page.locator('[data-testid="apply-promo-btn"]').click();
      await expect(page.locator('[data-testid="promo-applied-badge"]')).toBeVisible();
      await expect(page.locator('[data-testid="discount-amount"]')).toContainText('10%');
    }

    // 5. Complete booking and verify confirmation
    await page.locator('[data-testid="book-flight"]').click();
    await expect(page.locator('[data-testid="booking-confirmation"]')).toBeVisible();
    await expect(page.locator('[data-testid="booking-id"]')).toBeVisible();
  });
});
"""
        return code

    async def generate_test(
        self,
        changes: ChangeSet,
        impact: ImpactAnalysisResult,
        missing_scenario: str,
    ) -> GeneratedTest:
        """Generate a Playwright test candidate and statically validate it."""
        style_context = self._get_style_context()
        diff_snippet = "\n".join([f"File: {f.path}\n{f.diff[:800]}" for f in changes.files])

        user_prompt = f"""Generate a Playwright test for this missing scenario:
Scenario: {missing_scenario}

Change Details:
Summary: {impact.summary}
Diff:
{diff_snippet}

Existing Project Test Style:
{style_context}

Generate the complete test file code.
"""

        generated_code = ""
        try:
            response: LLMResponse = await self.llm_service.generate(
                prompt=user_prompt,
                system_prompt=TEST_GENERATOR_SYSTEM_PROMPT,
                max_tokens=1000,
                temperature=0.2,
            )
            raw = response.content.strip()

            # Clean markdown code fence if present
            code_match = re.search(r"```(?:typescript|ts)?\s*(.*?)\s*```", raw, re.DOTALL)
            if code_match:
                generated_code = code_match.group(1).strip()
            else:
                generated_code = raw

            # Ensure AI header is present
            if "Generated by TravelGuard AI" not in generated_code:
                generated_code = (
                    "/**\n * Generated by TravelGuard AI.\n * Review before promoting to the permanent test suite.\n */\n\n"
                    + generated_code
                )
        except Exception as exc:
            logger.warning(f"[AITestGenerator] LLM generation failed ({exc}); using grounded fallback.")
            generated_code = self._generate_fallback_code(missing_scenario, diff_snippet)

        # Slugify filename
        file_slug = "promo-code" if "promo" in missing_scenario.lower() else "generated-journey-test"
        target_file = self.target_dir / f"{file_slug}.spec.ts"

        # Validate generated code
        is_valid, errors = TestValidator.validate(str(target_file), generated_code)

        if not is_valid:
            # Attempt to use fallback if LLM generated invalid syntax
            logger.warning(f"[AITestGenerator] Generated code failed validation: {errors}. Retrying with deterministic fallback.")
            generated_code = self._generate_fallback_code(missing_scenario, diff_snippet)
            is_valid, errors = TestValidator.validate(str(target_file), generated_code)

        # Save to file
        target_file.write_text(generated_code, encoding="utf-8")

        rel_path = str(target_file.relative_to(self.repo_root))
        validation_status = "PASSED" if is_valid else "FAILED"
        validation_details = "All static syntax, import, and selector assertions verified." if is_valid else "; ".join(errors)

        return GeneratedTest(
            file_path=rel_path,
            code=generated_code,
            scenario_name=missing_scenario,
            journey_id=impact.affected_journeys[0].journey_id if impact.affected_journeys else "flight_booking",
            validation_status=validation_status,
            validation_details=validation_details,
        )
