"""Static validation for AI-generated Playwright tests."""

from pathlib import Path
import re
from typing import List, Tuple


class TestValidator:
    """Performs strict static quality and syntax validation on generated test code."""

    @classmethod
    def validate(cls, file_path: str, code: str) -> Tuple[bool, List[str]]:
        """
        Validate generated test file against safety and convention rules:
        1. File exists and is non-empty.
        2. Playwright test imports exist.
        3. Contains at least one test(...) declaration.
        4. Contains assertions expect(...).
        5. Prohibits arbitrary page.waitForTimeout().
        6. Validates bracket/brace/parenthesis balance.
        7. Contains TravelGuard AI header notice.
        """
        errors: List[str] = []

        if not code or len(code.strip()) < 50:
            errors.append("Generated code is too short or empty.")
            return False, errors

        # Rule 1: Check required Playwright import
        if "from '@playwright/test'" not in code and 'from "@playwright/test"' not in code:
            errors.append("Missing required Playwright import: import { test, expect } from '@playwright/test'.")

        # Rule 2: Check test() declaration
        if not re.search(r"\btest\s*\(", code) and not re.search(r"\btest\.describe\s*\(", code):
            errors.append("Missing standard Playwright test() or test.describe() block.")

        # Rule 3: Check expect(...) assertion
        if not re.search(r"\bexpect\s*\(", code):
            errors.append("Missing verification assertions (expect(...)).")

        # Rule 4: Ban arbitrary timeouts
        if "page.waitForTimeout" in code:
            errors.append("Prohibited pattern 'page.waitForTimeout()' detected; use explicit locator assertions.")

        # Rule 5: Check AI-generated disclaimer comment
        if "Generated by TravelGuard AI" not in code:
            errors.append("Missing required 'Generated by TravelGuard AI' notice header.")

        # Rule 6: Check bracket and brace balance
        open_curly = code.count("{")
        close_curly = code.count("}")
        if open_curly != close_curly:
            errors.append(f"Unbalanced curly braces (opened: {open_curly}, closed: {close_curly}).")

        open_paren = code.count("(")
        close_paren = code.count(")")
        if open_paren != close_paren:
            errors.append(f"Unbalanced parentheses (opened: {open_paren}, closed: {close_paren}).")

        is_valid = len(errors) == 0
        return is_valid, errors
